version: '3'
services:
  api:
    container_name: flask-api-dev
    build:
      context: .
      dockerfile: backend.dockerfile
    env_file:
      - .env
    ports:
      - '5000:5000'
    depends_on:
      - db

  db:
    image: postgres:9.6
    container_name: flask-postgres-dev
    env_file:
      - .env
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - pg_data_dev:/var/lib/postgresql/data/

  pgadmin:
    image: dpage/pgadmin4
    container_name: flask-pgadmin-container-dev
    depends_on:
      - db
    env_file:
      - .env
    restart: always
    ports:
    - "5050:5050"
    volumes:
    - pga4volume_dev:/var/lib/pgadmin

  redis:
    image: redis
    container_name: flask-redis-dev
    ports:
    - "6379:6379"


volumes:
  pg_data_dev:
  pga4volume_dev:
